// Hardcoded fallback repertoire — used by the public /repertoire page when
// the Song table is empty or unreachable, and consumed by `npm run db:seed`
// to one-shot import these into the DB so admin can manage them.
//
// This file has zero React imports so it can be loaded from a plain Node
// script (`tsx prisma/seed.ts`) without dragging in client dependencies.

import type { SongGenre } from "./genres";

export type DefaultSong = {
  title: string;
  artist?: string;
  genres: SongGenre[];
  recentlyAdded?: boolean;
  audioId?: string;
  audioUrl?: string;
};

const AUDIO_BASE = "https://hebbkx1anhila5yf.public.blob.vercel-storage.com";
const AUDIO_URLS = {
  rainbow: `${AUDIO_BASE}/Somewhere%20Over%20the%20Rainbow%20Mix%202-LkxgMx5yX3tj6LBGYGddBsd5DjS1Kw.mp3`,
  historia: `${AUDIO_BASE}/hdua%20master-E4v3tqBtfOoS5LTpV4b1Yggm4UT2jJ.mp3`,
  wonderful: `${AUDIO_BASE}/What%20a%20Wonderful%20World%20Master-JABmURSW0VZ53HYwZV3wGjLkjrgUcE.mp3`,
  bella: `${AUDIO_BASE}/7494-ec49-4177-b1d8-9f9050281eef-z3fhi0xnkvLcwbVHLJfejIs5W8Ki9t.mp3`,
  fly: `${AUDIO_BASE}/bd9e-0e62-408f-9954-d7de2da8f574-QJ0QV5BvfAdP40Lf4qkmkOPOJQ2DKe.mp3`,
  elvis: `${AUDIO_BASE}/Cant%20Help%20Falling%20in%20Love-gdzO839wZruU5nHq2wwSwsabROGJhT.mp3`,
};

export const defaultSongs: DefaultSong[] = [
  { title: "Air - Bach", artist: "Johann Sebastian Bach", genres: ["classical", "wedding"] },
  { title: "All I Ask of You", artist: "Phantom of the Opera", genres: ["film"] },
  { title: "All of Me", artist: "John Legend", genres: ["pop", "wedding"] },
  { title: "All of the Lights Interlude", artist: "Kanye West", genres: ["pop"] },
  { title: "Always on My Mind", artist: "Willie Nelson", genres: ["pop"] },
  { title: "Are You Lonesome Tonight", artist: "Elvis Presley", genres: ["pop"] },
  { title: "As it Was", artist: "Harry Styles", genres: ["pop"] },
  { title: "At Last", artist: "Etta James", genres: ["jazz", "wedding"] },
  { title: "Ave Maria", artist: "Franz Schubert", genres: ["classical", "sacred", "wedding"] },
  { title: "Averdici Roma", artist: "Traditional Italian", genres: ["italian"] },
  { title: "A Thousand Years", artist: "Christina Perri", genres: ["pop", "wedding"] },
  { title: "Bella Ciao", artist: "Traditional Italian", genres: ["italian"], audioId: "bella-ciao", audioUrl: AUDIO_URLS.bella },
  { title: "Besame Mucho", artist: "Consuelo Velázquez", genres: ["latin"] },
  { title: "Beth", artist: "Kiss", genres: ["pop"] },
  { title: "Blinding Lights", artist: "The Weeknd", genres: ["pop"] },
  { title: "Bless the Broken Road", artist: "Rascal Flatts", genres: ["pop", "wedding"] },
  { title: "Bohemian Rhapsody", artist: "Queen", genres: ["pop"] },
  { title: "Bridge Over Troubled Water", artist: "Simon & Garfunkel", genres: ["pop"] },
  { title: "Canon in D", artist: "Johann Pachelbel", genres: ["classical", "wedding"] },
  { title: "Can't Help Falling in Love", artist: "Elvis Presley", genres: ["pop", "wedding"], audioId: "cant-help-falling-in-love", audioUrl: AUDIO_URLS.elvis },
  { title: "Can't Take my Eyes off You", artist: "Frankie Valli", genres: ["pop", "wedding"] },
  { title: "Careless Whisper", artist: "George Michael", genres: ["pop"] },
  { title: "Caruso", artist: "Lucio Dalla", genres: ["italian", "classical"] },
  { title: "City of Stars (La La Land)", artist: "La La Land OST", genres: ["film"] },
  { title: "Circles", artist: "Post Malone", genres: ["pop"] },
  { title: "Cold Water", artist: "Major Lazer ft. Justin Bieber", genres: ["pop"] },
  { title: "Come as you Are", artist: "Nirvana", genres: ["pop"] },
  { title: "Come Back to Sorrento", artist: "Traditional Italian", genres: ["italian"] },
  { title: "Crying", artist: "Roy Orbison", genres: ["pop"] },
  { title: "Dancing Queen", artist: "ABBA", genres: ["pop"] },
  { title: "Despacito", artist: "Luis Fonsi", genres: ["latin", "pop"] },
  { title: "Die in Your Arms", artist: "Justin Bieber", genres: ["pop"] },
  { title: "Die With a Smile", artist: "Lady Gaga & Bruno Mars", genres: ["pop"] },
  { title: "Don't Start Now", artist: "Dua Lipa", genres: ["pop"] },
  { title: "Don't Stop Me Now", artist: "Queen", genres: ["pop"] },
  { title: "Don't stop believing", artist: "Journey", genres: ["pop"] },
  { title: "Dream On", artist: "Aerosmith", genres: ["pop"] },
  { title: "Drunken Sailor", artist: "Traditional Sea Shanty", genres: ["pop"] },
  { title: "Endless Love", artist: "Diana Ross & Lionel Richie", genres: ["pop", "wedding"] },
  { title: "Every Breath You Take", artist: "The Police", genres: ["pop", "wedding"] },
  { title: "Eye of the Tiger", artist: "Survivor", genres: ["pop"] },
  { title: "Flowers", artist: "Miley Cyrus", genres: ["pop"] },
  { title: "Fly Me to the Moon", artist: "Frank Sinatra", genres: ["jazz", "wedding"], audioId: "fly-me-to-the-moon", audioUrl: AUDIO_URLS.fly },
  { title: "Gimme Gimme Gimme", artist: "ABBA", genres: ["pop"] },
  { title: "Golden Hour", artist: "Kacey Musgraves", genres: ["pop"] },
  { title: "Goodness of God", artist: "Jenn Johnson", genres: ["sacred"] },
  { title: "Hallelujah", artist: "Leonard Cohen", genres: ["sacred", "pop"] },
  { title: "Hard to Say I'm Sorry", artist: "Chicago", genres: ["pop"] },
  { title: "Havana", artist: "Camila Cabello", genres: ["latin", "pop"] },
  { title: "Hava Nagila", artist: "Traditional Hebrew", genres: ["classical"] },
  { title: "Heart Shaped Box", artist: "Nirvana", genres: ["pop"] },
  { title: "Hey Jude", artist: "The Beatles", genres: ["pop"] },
  { title: "Historia De un Amor", artist: "Carlos Eleta Almarán", genres: ["latin"], audioId: "historia-de-un-amor", audioUrl: AUDIO_URLS.historia },
  { title: "Holy Forever", artist: "Chris Tomlin", genres: ["sacred"] },
  { title: "How Great Thou Art", artist: "Traditional Hymn", genres: ["sacred"] },
  { title: "I Don't Wanna Miss a Thing", artist: "Aerosmith", genres: ["pop", "wedding"] },
  { title: "I Feel it Coming", artist: "The Weeknd ft. Daft Punk", genres: ["pop"] },
  { title: "I Have a Dream", artist: "ABBA", genres: ["pop"] },
  { title: "If I Can Dream", artist: "Elvis Presley", genres: ["pop"] },
  { title: "I left my Heart in San Francisco", artist: "Tony Bennett", genres: ["jazz"] },
  { title: "I Loved Her First", artist: "Heartland", genres: ["pop", "wedding"] },
  { title: "Imagine", artist: "John Lennon", genres: ["pop"] },
  { title: "Irish Washerwoman", artist: "Traditional Irish", genres: ["classical"] },
  { title: "I Was Made For Lovin You", artist: "Kiss", genres: ["pop"] },
  { title: "Just the Two of Us", artist: "Bill Withers", genres: ["pop", "jazz"] },
  { title: "Kiss the Rain", artist: "Yiruma", genres: ["classical"] },
  { title: "La Bamba", artist: "Ritchie Valens", genres: ["latin"] },
  { title: "La Isla Bonita", artist: "Madonna", genres: ["latin", "pop"] },
  { title: "La La Land Main Theme", artist: "La La Land OST", genres: ["film"] },
  { title: "Lambada", artist: "Kaoma", genres: ["latin"] },
  { title: "La Paloma", artist: "Traditional Spanish", genres: ["latin", "classical"] },
  { title: "La Vie En Rose", artist: "Édith Piaf", genres: ["jazz", "film"] },
  { title: "Let It Be Me", artist: "The Everly Brothers", genres: ["pop"] },
  { title: "Let Me Love You", artist: "Mario", genres: ["pop"] },
  { title: "Let's Get Loud", artist: "Jennifer Lopez", genres: ["latin", "pop"] },
  { title: "Livin La Vida Loca", artist: "Ricky Martin", genres: ["latin", "pop"] },
  { title: "Living on a Prayer", artist: "Bon Jovi", genres: ["pop"] },
  { title: "Love in Portofino", artist: "Andrea Bocelli", genres: ["italian"] },
  { title: "Love Me Tender", artist: "Elvis Presley", genres: ["pop", "wedding"] },
  { title: "Love Never Felt So Good", artist: "Michael Jackson", genres: ["pop"] },
  { title: "Love of My Life", artist: "Queen", genres: ["pop", "wedding"] },
  { title: "Love Story", artist: "Taylor Swift", genres: ["pop", "wedding"] },
  { title: "Mama Mia", artist: "ABBA", genres: ["pop"] },
  { title: "Meditation de Thais", artist: "Jules Massenet", genres: ["classical", "wedding"] },
  { title: "Memory", artist: "Cats", genres: ["film"] },
  { title: "Minuets by Bach", artist: "Johann Sebastian Bach", genres: ["classical"] },
  { title: "Moon River", artist: "Henry Mancini", genres: ["jazz", "film"] },
  { title: "Music of the Night", artist: "Phantom of the Opera", genres: ["film"] },
  { title: "My Funny Valentine", artist: "Richard Rodgers", genres: ["jazz"] },
  { title: "My Heart Will Go On", artist: "Celine Dion", genres: ["film", "wedding"] },
  { title: "My Way", artist: "Frank Sinatra", genres: ["jazz"] },
  { title: "Nessun Dorma", artist: "Giacomo Puccini", genres: ["classical", "italian"] },
  { title: "Obsession", artist: "Aventura", genres: ["latin"] },
  { title: "O Canada", artist: "National Anthem", genres: ["classical"] },
  { title: "O Mio Babino Caro", artist: "Giacomo Puccini", genres: ["classical", "italian"] },
  { title: "Open Arms", artist: "Journey", genres: ["pop"] },
  { title: "O Sole Mio", artist: "Traditional Neapolitan", genres: ["italian", "classical"] },
  { title: "Over the Rainbow", artist: "Judy Garland", genres: ["jazz", "film"], audioId: "somewhere-over-the-rainbow", audioUrl: AUDIO_URLS.rainbow },
  { title: "Paint it Black", artist: "The Rolling Stones", genres: ["pop"] },
  { title: "Perfect", artist: "Ed Sheeran", genres: ["pop", "wedding"] },
  { title: "Pirates of the Caribbean", artist: "Hans Zimmer", genres: ["film"] },
  { title: "Put Your Head on My Shoulder", artist: "Paul Anka", genres: ["pop", "wedding"] },
  { title: "Quizas Quizas Quizas", artist: "Osvaldo Farrés", genres: ["latin"] },
  { title: "Rasputin", artist: "Boney M", genres: ["pop"] },
  { title: "River Flows in You", artist: "Yiruma", genres: ["classical"] },
  { title: "Rolling in the Deep", artist: "Adele", genres: ["pop"] },
  { title: "Santa Lucia", artist: "Traditional Neapolitan", genres: ["italian"] },
  { title: "Sara Perche Ti Amo", artist: "Ricchi e Poveri", genres: ["italian", "pop"] },
  { title: "Save Your Tears", artist: "The Weeknd", genres: ["pop"] },
  { title: "Senorita", artist: "Shawn Mendes & Camila Cabello", genres: ["latin", "pop"] },
  { title: "Serenade - Schubert", artist: "Franz Schubert", genres: ["classical", "wedding"] },
  { title: "Smells Like Teen Spirit", artist: "Nirvana", genres: ["pop"] },
  { title: "Someone Like You", artist: "Adele", genres: ["pop"] },
  { title: "Someone You Loved", artist: "Lewis Capaldi", genres: ["pop"] },
  { title: "Song to the Moon", artist: "Antonín Dvořák", genres: ["classical"] },
  { title: "Super Trouper", artist: "ABBA", genres: ["pop"] },
  { title: "Swan Lake", artist: "Pyotr Ilyich Tchaikovsky", genres: ["classical"] },
  { title: "Sway", artist: "Dean Martin", genres: ["jazz", "latin"] },
  { title: "Sweet Caroline", artist: "Neil Diamond", genres: ["pop"] },
  { title: "Talking to the Moon", artist: "Bruno Mars", genres: ["pop"] },
  { title: "Teenage Dream", artist: "Katy Perry", genres: ["pop"] },
  { title: "Tennessee Whiskey", artist: "Chris Stapleton", genres: ["pop"] },
  { title: "That's Amore", artist: "Dean Martin", genres: ["italian", "jazz"] },
  { title: "The Godfather Theme", artist: "Nino Rota", genres: ["film", "italian"] },
  { title: "The Lonely Shepard", artist: "James Last", genres: ["classical"] },
  { title: "The Swan", artist: "Camille Saint-Saëns", genres: ["classical", "wedding"] },
  { title: "The Way We Were", artist: "Barbra Streisand", genres: ["jazz"] },
  { title: "The Wonder of You", artist: "Elvis Presley", genres: ["pop"] },
  { title: "Thinking Out Loud", artist: "Ed Sheeran", genres: ["pop", "wedding"] },
  { title: "This Will Be an Everlasting Love", artist: "Natalie Cole", genres: ["pop", "wedding"] },
  { title: "Time to Say Goodbye", artist: "Andrea Bocelli", genres: ["classical", "italian"] },
  { title: "Titanium", artist: "David Guetta ft. Sia", genres: ["pop"] },
  { title: "Turning Page", artist: "Sleeping at Last", genres: ["pop", "wedding"] },
  { title: "Unchained Melody", artist: "The Righteous Brothers", genres: ["pop", "wedding"] },
  { title: "Until I Found You", artist: "Stephen Sanchez", genres: ["pop", "wedding"] },
  { title: "Uptown Girl", artist: "Billy Joel", genres: ["pop"] },
  { title: "Versace on the Floor", artist: "Bruno Mars", genres: ["pop"] },
  { title: "Viva La Vida", artist: "Coldplay", genres: ["pop"] },
  { title: "Vocalise", artist: "Sergei Rachmaninoff", genres: ["classical"] },
  { title: "Volare", artist: "Dean Martin", genres: ["italian", "jazz"] },
  { title: "Wake Me Up", artist: "Avicii", genres: ["pop"] },
  { title: "Waltz No. 2 by Shostakovich", artist: "Dmitri Shostakovich", genres: ["classical"] },
  { title: "We Are the Champions", artist: "Queen", genres: ["pop"] },
  { title: "What a Wonderful World", artist: "Louis Armstrong", genres: ["jazz", "wedding"], audioId: "what-a-wonderful-world", audioUrl: AUDIO_URLS.wonderful },
  { title: "Wildest Dreams", artist: "Taylor Swift", genres: ["pop"] },
  { title: "Yesterday", artist: "The Beatles", genres: ["pop"] },
  { title: "You Are The Reason", artist: "Calum Scott", genres: ["pop", "wedding"] },
  { title: "You Raise me Up", artist: "Josh Groban", genres: ["pop", "sacred", "wedding"] },

  // Recently Added (2026-04)
  { title: "Beauty and a Beat", artist: "Justin Bieber ft. Nicki Minaj", genres: ["pop"], recentlyAdded: true },
  { title: "Country Roads", artist: "John Denver", genres: ["pop"], recentlyAdded: true },
  { title: "Everybody Wants to Rule the World", artist: "Tears for Fears", genres: ["pop"], recentlyAdded: true },
  { title: "Heaven", artist: "Bryan Adams", genres: ["pop", "wedding"], recentlyAdded: true },
  { title: "Highway to Hell", artist: "AC/DC", genres: ["pop"], recentlyAdded: true },
  { title: "Holding Out for a Hero", artist: "Bonnie Tyler", genres: ["pop", "film"], recentlyAdded: true },
  { title: "Hotel California", artist: "Eagles", genres: ["pop"], recentlyAdded: true },
  { title: "I'm Good (Blue)", artist: "David Guetta & Bebe Rexha", genres: ["pop"], recentlyAdded: true },
  { title: "I Wanna Dance with Somebody", artist: "Whitney Houston", genres: ["pop"], recentlyAdded: true },
  { title: "I Will Survive", artist: "Gloria Gaynor", genres: ["pop"], recentlyAdded: true },
  { title: "It's Not Unusual", artist: "Tom Jones", genres: ["jazz", "pop"], recentlyAdded: true },
  { title: "It Will Rain", artist: "Bruno Mars", genres: ["pop"], recentlyAdded: true },
  { title: "Jessie's Girl", artist: "Rick Springfield", genres: ["pop"], recentlyAdded: true },
  { title: "Jump", artist: "Van Halen", genres: ["pop"], recentlyAdded: true },
  { title: "Last Friday Night", artist: "Katy Perry", genres: ["pop"], recentlyAdded: true },
  { title: "Lucky Star", artist: "Madonna", genres: ["pop"], recentlyAdded: true },
  { title: "Moth to a Flame", artist: "Swedish House Mafia & The Weeknd", genres: ["pop"], recentlyAdded: true },
  { title: "Over the Mountain", artist: "Ozzy Osbourne", genres: ["pop"], recentlyAdded: true },
  { title: "Quando Quando Quando", artist: "Tony Renis", genres: ["italian", "jazz"], recentlyAdded: true },
  { title: "September", artist: "Earth, Wind & Fire", genres: ["pop"], recentlyAdded: true },
  { title: "Shake It Off", artist: "Taylor Swift", genres: ["pop"], recentlyAdded: true },
  { title: "She's a Lady", artist: "Tom Jones", genres: ["pop"], recentlyAdded: true },
  { title: "Smooth Criminal", artist: "Michael Jackson", genres: ["pop"], recentlyAdded: true },
  { title: "Start Me Up", artist: "The Rolling Stones", genres: ["pop"], recentlyAdded: true },
  { title: "Summer Nights", artist: "Grease", genres: ["film", "pop"], recentlyAdded: true },
  { title: "Take on Me", artist: "a-ha", genres: ["pop"], recentlyAdded: true },
  { title: "Tarantella", artist: "Traditional Italian", genres: ["italian", "classical"], recentlyAdded: true },
  { title: "The Final Countdown", artist: "Europe", genres: ["pop"], recentlyAdded: true },
  { title: "Ti Amo", artist: "Umberto Tozzi", genres: ["italian", "pop"], recentlyAdded: true },
  { title: "Where Have You Been", artist: "Rihanna", genres: ["pop"], recentlyAdded: true },
  { title: "Where You Are", artist: "Moana", genres: ["film"], recentlyAdded: true },
  { title: "YMCA", artist: "Village People", genres: ["pop"], recentlyAdded: true },
];

// How long after createdAt a song is considered "recently added" on the
// public catalog. Drives the New badge auto-derivation.
export const RECENTLY_ADDED_WINDOW_DAYS = 60;
