"use client"
import { Card, CardContent } from "@/components/ui/card"
import { Music } from "lucide-react"
import { Badge } from "@/components/ui/badge"

interface Song {
  id: string
  title: string
  artist: string
  genre: string
  category: string
  duration: string
  description: string
}

export function SongCatalog() {
  // Full song catalog
  const allSongs: Song[] = [
    // Featured songs
    {
      id: "always-on-my-mind",
      title: "Always on My Mind",
      artist: "Willie Nelson",
      genre: "Country/Pop",
      category: "popular",
      duration: "3:42",
      description: "A timeless classic perfect for romantic moments",
    },
    {
      id: "all-i-ask-of-you",
      title: "All I Ask of You",
      artist: "Phantom of the Opera",
      genre: "Musical Theatre",
      category: "musical",
      duration: "4:15",
      description: "Beautiful duet from the beloved musical",
    },
    {
      id: "all-of-me",
      title: "All of Me",
      artist: "John Legend",
      genre: "Contemporary",
      category: "popular",
      duration: "4:29",
      description: "Modern love song, perfect for weddings",
    },
    {
      id: "are-you-lonesome-tonight",
      title: "Are You Lonesome Tonight",
      artist: "Elvis Presley",
      genre: "Classic Pop",
      category: "popular",
      duration: "3:06",
      description: "Nostalgic ballad with emotional depth",
    },
    {
      id: "as-it-was",
      title: "As It Was",
      artist: "Harry Styles",
      genre: "Pop",
      category: "popular",
      duration: "2:47",
      description: "Contemporary hit with beautiful melodies",
    },
    // Additional songs
    {
      id: "all-of-the-lights",
      title: "All of the Lights Interlude",
      artist: "Kanye West",
      genre: "Hip Hop",
      category: "popular",
      duration: "1:58",
      description: "Instrumental interlude from the award-winning album",
    },
    {
      id: "air-bach",
      title: "Air (Bach)",
      artist: "Johann Sebastian Bach",
      genre: "Classical",
      category: "classical",
      duration: "5:15",
      description: "Elegant classical piece, perfect for ceremonies",
    },
    {
      id: "at-last",
      title: "At Last",
      artist: "Etta James",
      genre: "Jazz",
      category: "jazz",
      duration: "3:02",
      description: "Soulful jazz standard for romantic moments",
    },
    {
      id: "ave-maria",
      title: "Ave Maria",
      artist: "Franz Schubert",
      genre: "Classical",
      category: "classical",
      duration: "4:50",
      description: "Timeless classical piece for religious ceremonies",
    },
    {
      id: "a-thousand-years",
      title: "A Thousand Years",
      artist: "Christina Perri",
      genre: "Pop",
      category: "popular",
      duration: "4:45",
      description: "Contemporary love song popular for weddings",
    },
    {
      id: "viva-la-vida",
      title: "Viva La Vida",
      artist: "Coldplay",
      genre: "Alternative Rock",
      category: "popular",
      duration: "4:02",
      description: "Upbeat contemporary piece with orchestral elements",
    },
    {
      id: "volare",
      title: "Volare",
      artist: "Dean Martin",
      genre: "Italian Pop",
      category: "jazz",
      duration: "3:00",
      description: "Classic Italian song with a joyful melody",
    },
    {
      id: "wildest-dreams",
      title: "Wildest Dreams",
      artist: "Taylor Swift",
      genre: "Pop",
      category: "popular",
      duration: "3:40",
      description: "Dreamy pop song with romantic lyrics",
    },
    {
      id: "yesterday",
      title: "Yesterday",
      artist: "The Beatles",
      genre: "Rock",
      category: "popular",
      duration: "2:05",
      description: "Iconic ballad that works beautifully on violin",
    },
    {
      id: "you-raise-me-up",
      title: "You Raise Me Up",
      artist: "Josh Groban",
      genre: "Classical Crossover",
      category: "popular",
      duration: "4:56",
      description: "Inspirational piece perfect for ceremonies",
    },
    {
      id: "the-way-we-were",
      title: "The Way We Were",
      artist: "Barbra Streisand",
      genre: "Pop",
      category: "popular",
      duration: "3:30",
      description: "Nostalgic ballad with emotional resonance",
    },
    // Additional classical pieces
    {
      id: "canon-in-d",
      title: "Canon in D",
      artist: "Johann Pachelbel",
      genre: "Classical",
      category: "classical",
      duration: "5:30",
      description: "Popular classical piece for wedding ceremonies",
    },
    {
      id: "four-seasons-spring",
      title: "Four Seasons: Spring",
      artist: "Antonio Vivaldi",
      genre: "Classical",
      category: "classical",
      duration: "3:35",
      description: "Bright and lively classical masterpiece",
    },
    // Additional jazz standards
    {
      id: "fly-me-to-the-moon",
      title: "Fly Me to the Moon",
      artist: "Frank Sinatra",
      genre: "Jazz",
      category: "jazz",
      duration: "2:30",
      description: "Classic jazz standard with a swinging feel",
    },
    {
      id: "moon-river",
      title: "Moon River",
      artist: "Henry Mancini",
      genre: "Jazz",
      category: "jazz",
      duration: "2:45",
      description: "Elegant jazz ballad from Breakfast at Tiffany's",
    },
    // Additional musical theater pieces
    {
      id: "memory",
      title: "Memory",
      artist: "Cats",
      genre: "Musical Theatre",
      category: "musical",
      duration: "4:15",
      description: "Emotional ballad from the musical Cats",
    },
    {
      id: "think-of-me",
      title: "Think of Me",
      artist: "Phantom of the Opera",
      genre: "Musical Theatre",
      category: "musical",
      duration: "3:35",
      description: "Beautiful aria from Phantom of the Opera",
    },
    {
      id: "despacito",
      title: "Despacito",
      artist: "Luis Fonsi ft. Daddy Yankee",
      genre: "Latin Pop",
      category: "popular",
      duration: "3:47",
      description: "Global hit with infectious Latin rhythms, beautifully adapted for violin",
    },
    {
      id: "cant-help-falling-in-love",
      title: "Can't Help Falling in Love",
      artist: "Elvis Presley",
      genre: "Classic Pop",
      category: "popular",
      duration: "3:02",
      description: "Timeless romantic ballad perfect for weddings and special moments",
    },
    {
      id: "sweet-caroline",
      title: "Sweet Caroline",
      artist: "Neil Diamond",
      genre: "Pop Rock",
      category: "popular",
      duration: "3:21",
      description: "Beloved sing-along anthem that brings joy to any celebration",
    },
    {
      id: "dancing-queen",
      title: "Dancing Queen",
      artist: "ABBA",
      genre: "Pop",
      category: "popular",
      duration: "3:51",
      description: "Disco classic with uplifting melodies perfect for celebrations",
    },
    {
      id: "averdici-roma",
      title: "Averdici Roma",
      artist: "Traditional Italian",
      genre: "Italian Folk",
      category: "classical",
      duration: "3:15",
      description: "Beautiful Italian folk song with romantic melodies",
    },
    {
      id: "bella-ciao",
      title: "Bella Ciao",
      artist: "Traditional Italian",
      genre: "Folk",
      category: "popular",
      duration: "2:45",
      description: "Famous Italian folk song with powerful emotional resonance",
    },
    {
      id: "besame-mucho",
      title: "Besame Mucho",
      artist: "Consuelo Velázquez",
      genre: "Latin",
      category: "jazz",
      duration: "3:30",
      description: "Classic Latin love song perfect for romantic occasions",
    },
    {
      id: "beth",
      title: "Beth",
      artist: "Kiss",
      genre: "Rock Ballad",
      category: "popular",
      duration: "2:47",
      description: "Emotional rock ballad that translates beautifully to violin",
    },
    {
      id: "blinding-lights",
      title: "Blinding Lights",
      artist: "The Weeknd",
      genre: "Pop",
      category: "popular",
      duration: "3:20",
      description: "Modern hit with nostalgic 80s vibes",
    },
    {
      id: "bohemian-rhapsody",
      title: "Bohemian Rhapsody",
      artist: "Queen",
      genre: "Rock",
      category: "popular",
      duration: "5:55",
      description: "Epic rock masterpiece adapted for violin performance",
    },
    {
      id: "bridge-over-troubled-water",
      title: "Bridge Over Troubled Water",
      artist: "Simon & Garfunkel",
      genre: "Folk Rock",
      category: "popular",
      duration: "4:52",
      description: "Timeless ballad with uplifting message",
    },
    {
      id: "cant-take-my-eyes-off-you",
      title: "Can't Take My Eyes Off You",
      artist: "Frankie Valli",
      genre: "Pop",
      category: "popular",
      duration: "3:17",
      description: "Classic love song perfect for weddings",
    },
    {
      id: "caruso",
      title: "Caruso",
      artist: "Lucio Dalla",
      genre: "Italian Pop",
      category: "classical",
      duration: "4:25",
      description: "Passionate Italian ballad with operatic qualities",
    },
    {
      id: "careless-whisper",
      title: "Careless Whisper",
      artist: "George Michael",
      genre: "Pop",
      category: "popular",
      duration: "5:00",
      description: "Iconic saxophone melody adapted beautifully for violin",
    },
    {
      id: "city-of-stars",
      title: "City of Stars (La La Land)",
      artist: "La La Land Soundtrack",
      genre: "Musical",
      category: "musical",
      duration: "2:07",
      description: "Dreamy ballad from the acclaimed musical film",
    },
    {
      id: "circles",
      title: "Circles",
      artist: "Post Malone",
      genre: "Pop",
      category: "popular",
      duration: "3:35",
      description: "Contemporary hit with melodic appeal",
    },
    {
      id: "come-back-to-sorrento",
      title: "Come Back to Sorrento",
      artist: "Traditional Italian",
      genre: "Italian Folk",
      category: "classical",
      duration: "3:45",
      description: "Classic Italian song evoking the beauty of Sorrento",
    },
    {
      id: "cold-water",
      title: "Cold Water",
      artist: "Major Lazer ft. Justin Bieber",
      genre: "Pop",
      category: "popular",
      duration: "3:07",
      description: "Modern pop hit with emotional depth",
    },
    {
      id: "dont-start-now",
      title: "Don't Start Now",
      artist: "Dua Lipa",
      genre: "Pop",
      category: "popular",
      duration: "3:03",
      description: "Upbeat contemporary pop with disco influences",
    },
    {
      id: "drunken-sailor",
      title: "Drunken Sailor",
      artist: "Traditional Sea Shanty",
      genre: "Folk",
      category: "popular",
      duration: "2:30",
      description: "Traditional sea shanty with lively rhythm",
    },
    {
      id: "endless-love",
      title: "Endless Love",
      artist: "Diana Ross & Lionel Richie",
      genre: "R&B",
      category: "popular",
      duration: "4:24",
      description: "Romantic duet perfect for special moments",
    },
    {
      id: "flowers",
      title: "Flowers",
      artist: "Miley Cyrus",
      genre: "Pop",
      category: "popular",
      duration: "3:20",
      description: "Contemporary empowerment anthem",
    },
    {
      id: "golden-hour",
      title: "Golden Hour",
      artist: "Kacey Musgraves",
      genre: "Country Pop",
      category: "popular",
      duration: "3:29",
      description: "Beautiful country-pop ballad about love",
    },
    {
      id: "hallelujah",
      title: "Hallelujah",
      artist: "Leonard Cohen",
      genre: "Folk",
      category: "popular",
      duration: "4:36",
      description: "Spiritual and emotional masterpiece",
    },
    {
      id: "happy-birthday",
      title: "Happy Birthday",
      artist: "Traditional",
      genre: "Traditional",
      category: "popular",
      duration: "0:30",
      description: "Classic birthday celebration song",
    },
    {
      id: "hard-to-say-im-sorry",
      title: "Hard to Say I'm Sorry",
      artist: "Chicago",
      genre: "Rock",
      category: "popular",
      duration: "3:41",
      description: "Heartfelt ballad with beautiful melodies",
    },
    {
      id: "havana",
      title: "Havana",
      artist: "Camila Cabello",
      genre: "Latin Pop",
      category: "popular",
      duration: "3:37",
      description: "Latin-influenced pop hit with infectious rhythm",
    },
    {
      id: "historia-de-un-amor",
      title: "Historia De un Amor",
      artist: "Carlos Eleta Almarán",
      genre: "Latin",
      category: "jazz",
      duration: "3:15",
      description: "Classic Latin love song with passionate melodies",
    },
    {
      id: "hava-nagila",
      title: "Hava Nagila",
      artist: "Traditional Hebrew",
      genre: "Traditional",
      category: "classical",
      duration: "2:45",
      description: "Joyful Hebrew folk song for celebrations",
    },
    {
      id: "hey-jude",
      title: "Hey Jude",
      artist: "The Beatles",
      genre: "Rock",
      category: "popular",
      duration: "7:11",
      description: "Epic Beatles anthem with uplifting message",
    },
    {
      id: "how-great-thou-art",
      title: "How Great Thou Art",
      artist: "Traditional Hymn",
      genre: "Religious",
      category: "classical",
      duration: "4:10",
      description: "Beloved hymn perfect for religious ceremonies",
    },
    {
      id: "i-dont-wanna-miss-a-thing",
      title: "I Don't Wanna Miss a Thing",
      artist: "Aerosmith",
      genre: "Rock Ballad",
      category: "popular",
      duration: "4:59",
      description: "Powerful rock ballad about love and devotion",
    },
    {
      id: "imagine",
      title: "Imagine",
      artist: "John Lennon",
      genre: "Rock",
      category: "popular",
      duration: "3:07",
      description: "Peaceful anthem with hopeful message",
    },
    {
      id: "irish-washerwoman",
      title: "Irish Washerwoman",
      artist: "Traditional Irish",
      genre: "Celtic",
      category: "classical",
      duration: "2:20",
      description: "Lively Irish folk tune perfect for celebrations",
    },
    {
      id: "if-i-can-dream",
      title: "If I Can Dream",
      artist: "Elvis Presley",
      genre: "Pop",
      category: "popular",
      duration: "3:12",
      description: "Inspirational Elvis ballad with powerful message",
    },
    {
      id: "i-loved-her-first",
      title: "I Loved Her First",
      artist: "Heartland",
      genre: "Country",
      category: "popular",
      duration: "4:21",
      description: "Emotional father-daughter wedding song",
    },
    {
      id: "i-feel-it-coming",
      title: "I Feel It Coming",
      artist: "The Weeknd ft. Daft Punk",
      genre: "Pop",
      category: "popular",
      duration: "4:29",
      description: "Smooth contemporary hit with retro vibes",
    },
    {
      id: "just-the-two-of-us",
      title: "Just the Two of Us",
      artist: "Bill Withers",
      genre: "R&B",
      category: "jazz",
      duration: "3:59",
      description: "Smooth jazz-influenced love song",
    },
    {
      id: "kiss-the-rain",
      title: "Kiss the Rain",
      artist: "Yiruma",
      genre: "Contemporary Classical",
      category: "classical",
      duration: "4:28",
      description: "Beautiful contemporary piano piece adapted for violin",
    },
    {
      id: "lambada",
      title: "Lambada",
      artist: "Kaoma",
      genre: "Latin",
      category: "popular",
      duration: "3:26",
      description: "Energetic Latin dance hit",
    },
    {
      id: "la-isla-bonita",
      title: "La Isla Bonita",
      artist: "Madonna",
      genre: "Latin Pop",
      category: "popular",
      duration: "4:02",
      description: "Latin-influenced pop hit with tropical vibes",
    },
    {
      id: "la-vie-en-rose",
      title: "La Vie En Rose",
      artist: "Édith Piaf",
      genre: "French Chanson",
      category: "jazz",
      duration: "3:05",
      description: "Classic French love song with romantic charm",
    },
    {
      id: "la-bamba",
      title: "La Bamba",
      artist: "Ritchie Valens",
      genre: "Rock",
      category: "popular",
      duration: "2:07",
      description: "Upbeat rock and roll with Mexican folk influences",
    },
    {
      id: "la-la-land-main-theme",
      title: "La La Land Main Theme",
      artist: "La La Land Soundtrack",
      genre: "Musical",
      category: "musical",
      duration: "3:45",
      description: "Romantic main theme from the acclaimed musical film",
    },
    {
      id: "la-paloma",
      title: "La Paloma",
      artist: "Traditional Spanish",
      genre: "Spanish Folk",
      category: "classical",
      duration: "3:30",
      description: "Classic Spanish song with beautiful melodies",
    },
    {
      id: "lets-get-loud",
      title: "Let's Get Loud",
      artist: "Jennifer Lopez",
      genre: "Latin Pop",
      category: "popular",
      duration: "3:59",
      description: "Energetic Latin pop anthem",
    },
    {
      id: "let-it-be-me",
      title: "Let It Be Me",
      artist: "The Everly Brothers",
      genre: "Pop",
      category: "popular",
      duration: "2:33",
      description: "Romantic ballad perfect for intimate moments",
    },
    {
      id: "livin-la-vida-loca",
      title: "Livin La Vida Loca",
      artist: "Ricky Martin",
      genre: "Latin Pop",
      category: "popular",
      duration: "4:03",
      description: "High-energy Latin pop hit",
    },
    {
      id: "let-me-love-you",
      title: "Let Me Love You",
      artist: "Mario",
      genre: "R&B",
      category: "popular",
      duration: "4:28",
      description: "Smooth R&B love song",
    },
    {
      id: "love-in-portofino",
      title: "Love in Portofino",
      artist: "Andrea Bocelli",
      genre: "Classical Crossover",
      category: "classical",
      duration: "4:15",
      description: "Romantic Italian ballad with operatic qualities",
    },
    {
      id: "love-never-felt-so-good",
      title: "Love Never Felt So Good",
      artist: "Michael Jackson",
      genre: "Pop",
      category: "popular",
      duration: "2:54",
      description: "Upbeat Michael Jackson classic",
    },
    {
      id: "love-me-tender",
      title: "Love Me Tender",
      artist: "Elvis Presley",
      genre: "Country",
      category: "popular",
      duration: "2:42",
      description: "Gentle Elvis ballad perfect for romantic moments",
    },
    {
      id: "love-of-my-life",
      title: "Love of My Life",
      artist: "Queen",
      genre: "Rock Ballad",
      category: "popular",
      duration: "3:38",
      description: "Beautiful Queen ballad about deep love",
    },
    {
      id: "love-story",
      title: "Love Story",
      artist: "Taylor Swift",
      genre: "Country Pop",
      category: "popular",
      duration: "3:55",
      description: "Modern fairy tale love song",
    },
    {
      id: "meditation-de-thais",
      title: "Meditation de Thais",
      artist: "Jules Massenet",
      genre: "Classical",
      category: "classical",
      duration: "5:30",
      description: "Exquisite classical piece perfect for ceremonies",
    },
    {
      id: "minuets-by-bach",
      title: "Minuets by Bach",
      artist: "Johann Sebastian Bach",
      genre: "Classical",
      category: "classical",
      duration: "4:00",
      description: "Elegant baroque dance movements",
    },
    {
      id: "my-heart-will-go-on",
      title: "My Heart Will Go On",
      artist: "Celine Dion",
      genre: "Pop Ballad",
      category: "popular",
      duration: "4:40",
      description: "Epic love theme from Titanic",
    },
    {
      id: "my-way",
      title: "My Way",
      artist: "Frank Sinatra",
      genre: "Traditional Pop",
      category: "jazz",
      duration: "4:35",
      description: "Classic Sinatra anthem about living life on your terms",
    },
    {
      id: "my-funny-valentine",
      title: "My Funny Valentine",
      artist: "Richard Rodgers",
      genre: "Jazz Standard",
      category: "jazz",
      duration: "3:20",
      description: "Timeless jazz standard perfect for intimate settings",
    },
    {
      id: "nessun-dorma",
      title: "Nessun Dorma",
      artist: "Giacomo Puccini",
      genre: "Opera",
      category: "classical",
      duration: "3:21",
      description: "Powerful operatic aria adapted for violin",
    },
    {
      id: "obsession",
      title: "Obsession",
      artist: "Aventura",
      genre: "Bachata",
      category: "popular",
      duration: "4:22",
      description: "Popular bachata hit with romantic themes",
    },
    {
      id: "o-sole-mio",
      title: "O Sole Mio",
      artist: "Traditional Neapolitan",
      genre: "Italian Folk",
      category: "classical",
      duration: "3:15",
      description: "Classic Neapolitan song celebrating the sun",
    },
    {
      id: "o-canada",
      title: "O Canada",
      artist: "National Anthem",
      genre: "Patriotic",
      category: "classical",
      duration: "1:45",
      description: "Canadian national anthem",
    },
    {
      id: "over-the-rainbow",
      title: "Over the Rainbow",
      artist: "Judy Garland",
      genre: "Musical",
      category: "musical",
      duration: "2:42",
      description: "Timeless song of hope and dreams from The Wizard of Oz",
    },
    {
      id: "o-mio-babino-caro",
      title: "O Mio Babino Caro",
      artist: "Giacomo Puccini",
      genre: "Opera",
      category: "classical",
      duration: "2:30",
      description: "Beautiful operatic aria from Gianni Schicchi",
    },
    {
      id: "open-arms",
      title: "Open Arms",
      artist: "Journey",
      genre: "Rock Ballad",
      category: "popular",
      duration: "3:20",
      description: "Emotional rock ballad about love and longing",
    },
    {
      id: "perfect",
      title: "Perfect",
      artist: "Ed Sheeran",
      genre: "Pop",
      category: "popular",
      duration: "4:23",
      description: "Modern romantic ballad perfect for weddings",
    },
    {
      id: "pirates-of-the-caribbean",
      title: "Pirates of the Caribbean",
      artist: "Hans Zimmer",
      genre: "Film Score",
      category: "popular",
      duration: "3:30",
      description: "Epic adventure theme from the beloved film series",
    },
    {
      id: "put-your-head-on-my-shoulder",
      title: "Put Your Head on My Shoulder",
      artist: "Paul Anka",
      genre: "Pop",
      category: "popular",
      duration: "2:35",
      description: "Sweet romantic ballad from the 1950s",
    },
    {
      id: "quizas-quizas-quizas",
      title: "Quizas Quizas Quizas",
      artist: "Osvaldo Farrés",
      genre: "Latin",
      category: "jazz",
      duration: "3:10",
      description: "Classic Latin jazz standard",
    },
    {
      id: "river-flows-in-you",
      title: "River Flows in You",
      artist: "Yiruma",
      genre: "Contemporary Classical",
      category: "classical",
      duration: "3:20",
      description: "Beautiful contemporary piano piece adapted for violin",
    },
    {
      id: "save-your-tears",
      title: "Save Your Tears",
      artist: "The Weeknd",
      genre: "Pop",
      category: "popular",
      duration: "3:35",
      description: "Contemporary hit with emotional depth",
    },
    {
      id: "sara-perche-ti-amo",
      title: "Sara Perche Ti Amo",
      artist: "Ricchi e Poveri",
      genre: "Italian Pop",
      category: "popular",
      duration: "4:05",
      description: "Classic Italian love song",
    },
    {
      id: "senorita",
      title: "Senorita",
      artist: "Shawn Mendes & Camila Cabello",
      genre: "Latin Pop",
      category: "popular",
      duration: "3:11",
      description: "Contemporary Latin-influenced duet",
    },
    {
      id: "serenade-schubert",
      title: "Serenade - Schubert",
      artist: "Franz Schubert",
      genre: "Classical",
      category: "classical",
      duration: "3:45",
      description: "Romantic classical serenade perfect for intimate moments",
    },
    {
      id: "sway",
      title: "Sway",
      artist: "Dean Martin",
      genre: "Latin Jazz",
      category: "jazz",
      duration: "2:54",
      description: "Smooth Latin jazz standard perfect for dancing",
    },
    {
      id: "swan-lake",
      title: "Swan Lake",
      artist: "Pyotr Ilyich Tchaikovsky",
      genre: "Classical Ballet",
      category: "classical",
      duration: "4:30",
      description: "Iconic ballet theme with graceful melodies",
    },
    {
      id: "santa-lucia",
      title: "Santa Lucia",
      artist: "Traditional Neapolitan",
      genre: "Italian Folk",
      category: "classical",
      duration: "3:00",
      description: "Traditional Neapolitan song about the beautiful harbor",
    },
    {
      id: "song-to-the-moon",
      title: "Song to the Moon",
      artist: "Antonín Dvořák",
      genre: "Opera",
      category: "classical",
      duration: "5:45",
      description: "Beautiful operatic aria from Rusalka",
    },
    {
      id: "talking-to-the-moon",
      title: "Talking to the Moon",
      artist: "Bruno Mars",
      genre: "Pop",
      category: "popular",
      duration: "3:38",
      description: "Emotional ballad about longing and love",
    },
    {
      id: "the-godfather-theme",
      title: "The Godfather Theme",
      artist: "Nino Rota",
      genre: "Film Score",
      category: "popular",
      duration: "2:45",
      description: "Iconic theme from the classic film",
    },
    {
      id: "the-swan",
      title: "The Swan",
      artist: "Camille Saint-Saëns",
      genre: "Classical",
      category: "classical",
      duration: "2:35",
      description: "Elegant classical piece from Carnival of the Animals",
    },
    {
      id: "teenage-dream",
      title: "Teenage Dream",
      artist: "Katy Perry",
      genre: "Pop",
      category: "popular",
      duration: "3:48",
      description: "Upbeat pop anthem about young love",
    },
    {
      id: "thats-amore",
      title: "That's Amore",
      artist: "Dean Martin",
      genre: "Traditional Pop",
      category: "popular",
      duration: "3:05",
      description: "Classic Italian-American love song",
    },
    {
      id: "thinking-out-loud",
      title: "Thinking Out Loud",
      artist: "Ed Sheeran",
      genre: "Pop",
      category: "popular",
      duration: "4:41",
      description: "Romantic ballad perfect for first dances",
    },
    {
      id: "titanium",
      title: "Titanium",
      artist: "David Guetta ft. Sia",
      genre: "Electronic Pop",
      category: "popular",
      duration: "4:05",
      description: "Powerful anthem about strength and resilience",
    },
    {
      id: "time-to-say-goodbye",
      title: "Time to Say Goodbye",
      artist: "Andrea Bocelli & Sarah Brightman",
      genre: "Classical Crossover",
      category: "classical",
      duration: "4:05",
      description: "Emotional operatic duet",
    },
    {
      id: "turning-page",
      title: "Turning Page",
      artist: "Sleeping at Last",
      genre: "Indie Folk",
      category: "popular",
      duration: "4:15",
      description: "Beautiful love song from the Twilight soundtrack",
    },
    {
      id: "the-lonely-shepard",
      title: "The Lonely Shepard",
      artist: "James Last",
      genre: "Easy Listening",
      category: "popular",
      duration: "3:20",
      description: "Haunting melody made famous by Kill Bill",
    },
    {
      id: "the-wonder-of-you",
      title: "The Wonder of You",
      artist: "Elvis Presley",
      genre: "Pop",
      category: "popular",
      duration: "2:38",
      description: "Tender Elvis love song",
    },
    {
      id: "until-i-found-you",
      title: "Until I Found You",
      artist: "Stephen Sanchez",
      genre: "Pop",
      category: "popular",
      duration: "2:57",
      description: "Contemporary romantic ballad with vintage feel",
    },
    {
      id: "unchained-melody",
      title: "Unchained Melody",
      artist: "The Righteous Brothers",
      genre: "Soul",
      category: "popular",
      duration: "3:36",
      description: "Timeless love song perfect for romantic moments",
    },
    {
      id: "uptown-girl",
      title: "Uptown Girl",
      artist: "Billy Joel",
      genre: "Pop Rock",
      category: "popular",
      duration: "3:17",
      description: "Upbeat Billy Joel classic",
    },
    {
      id: "versace-on-the-floor",
      title: "Versace on the Floor",
      artist: "Bruno Mars",
      genre: "R&B",
      category: "popular",
      duration: "4:21",
      description: "Smooth contemporary R&B ballad",
    },
    {
      id: "vocalise",
      title: "Vocalise",
      artist: "Sergei Rachmaninoff",
      genre: "Classical",
      category: "classical",
      duration: "6:30",
      description: "Beautiful wordless classical piece",
    },
    {
      id: "wake-me-up",
      title: "Wake Me Up",
      artist: "Avicii",
      genre: "Electronic",
      category: "popular",
      duration: "4:07",
      description: "Uplifting electronic anthem",
    },
    {
      id: "waltz-no-2-shostakovich",
      title: "Waltz No. 2 by Shostakovich",
      artist: "Dmitri Shostakovich",
      genre: "Classical",
      category: "classical",
      duration: "3:30",
      description: "Elegant waltz from the Soviet composer",
    },
    {
      id: "what-a-wonderful-world",
      title: "What a Wonderful World",
      artist: "Louis Armstrong",
      genre: "Jazz",
      category: "jazz",
      duration: "2:21",
      description: "Optimistic jazz standard celebrating life's beauty",
    },
    {
      id: "you-are-the-reason",
      title: "You Are The Reason",
      artist: "Calum Scott",
      genre: "Pop Ballad",
      category: "popular",
      duration: "3:23",
      description: "Emotional contemporary ballad about love",
    },
  ]

  const filteredSongs = allSongs

  return (
    <div className="space-y-4 sm:space-y-6">
      {/* Songs Grid */}
      <div className="grid gap-3 sm:gap-4 md:gap-6">
        {filteredSongs.length > 0 ? (
          filteredSongs.map((song) => (
            <Card key={song.id} className="group hover:shadow-md transition-shadow duration-200">
              <CardContent className="p-4 sm:p-6">
                <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 sm:gap-4">
                  <div className="flex items-start gap-3 sm:gap-4 min-w-0 flex-1">
                    <div className="flex-shrink-0 mt-1">
                      <div className="w-8 h-8 sm:w-10 sm:h-10 rounded-full bg-primary/10 flex items-center justify-center">
                        <Music className="w-4 h-4 sm:w-5 sm:h-5 text-primary" />
                      </div>
                    </div>
                    <div className="min-w-0 flex-1">
                      <h3 className="font-medium text-sm sm:text-base leading-tight mb-1 truncate">{song.title}</h3>
                      <p className="text-xs sm:text-sm text-muted-foreground mb-2 truncate">{song.artist}</p>
                      <p className="text-xs sm:text-sm text-muted-foreground leading-relaxed line-clamp-2">
                        {song.description}
                      </p>
                    </div>
                  </div>
                  <div className="flex items-center justify-between sm:justify-end gap-3 sm:gap-4 flex-shrink-0">
                    <div className="flex items-center gap-2 sm:gap-3">
                      <Badge variant="secondary" className="text-xs px-2 py-1 font-normal">
                        {song.genre}
                      </Badge>
                      <span className="text-xs sm:text-sm text-muted-foreground font-mono">{song.duration}</span>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))
        ) : (
          <div className="text-center py-8 sm:py-12">
            <div className="w-16 h-16 sm:w-20 sm:h-20 mx-auto mb-4 rounded-full bg-muted flex items-center justify-center">
              <Music className="w-8 h-8 sm:w-10 sm:h-10 text-muted-foreground" />
            </div>
            <div>
              <h3 className="text-base sm:text-lg font-medium">No songs found</h3>
              <p className="text-sm text-muted-foreground mt-1 max-w-sm mx-auto">
                Please check back later for more songs in our repertoire
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
